#
# log4j
#
# appender1
#
log4j.appender.A1 = org.apache.log4j.FileAppender
log4j.appender.A1.append = false
log4j.appender.A1.File = c:/xlog/pc1_root.log
# appender2
#
log4j.appender.A2 = org.apache.log4j.FileAppender
log4j.appender.A2.append = false
log4j.appender.A2.File = c:/xlog/pc1_second.log
# appender3
#
log4j.appender.A3 = org.apache.log4j.FileAppender
log4j.appender.A3.append = false
log4j.appender.A3.File = c:/xlog/pc1_third.log
#
# Layout1
#
log4j.appender.A1.layout = org.apache.log4j.PatternLayout
log4j.appender.A1.layout.ConversionPattern = %d{yy-MM-dd HH:mm:ss} %-5p %c - %m%n
#
# Layout2
#
log4j.appender.A2.layout = org.apache.log4j.PatternLayout
log4j.appender.A2.layout.ConversionPattern = %d{yy-MM-dd HH:mm:ss} %-5p %c - %m%n
#
# Layout3
#
log4j.appender.A3.layout = org.apache.log4j.PatternLayout
log4j.appender.A3.layout.ConversionPattern = %d{yy-MM-dd HH:mm:ss} %-5p %c - %m%n
#
# category
#

log4j.rootLogger    = debug, A1
#log4j.logger.meibo  = debug, A2

#log4j.logger.teacher    = debug, A2
#log4j.logger.login      = debug, A2
#log4j.logger.student    = debug, A2
#log4j.logger.kamoku     = debug, A3
#log4j.logger.net.tkx.kamokuparser  = debug, A3

#log4j.logger.teacher      = debug, A1
#log4j.logger.database     = debug, A1
#log4j.net.tkx.jef         = debug, A2

#log4j.logger.database     = debug, A2
#log4j.logger.teacher      = debug, A3
#log4j.logger.kamoku       = debug, A3
#log4j.logger.transport    = debug, A3
#